package com.lse.admin.model;

import java.time.LocalDate;

import org.apache.poi.ss.usermodel.Cell;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter

public class Product {

  /**
   * internal id generated by the app
   */
  private final String id;

  /**
   * externally provided code; typically generated by the administration team
   */
  private final int code;

  private final String type;

  private final String description;

  /**
   * price at which the product has been bought
   */
  private double buyUnitPrice;

  /**
   * price at which the product has been planned to be sold
   */
  private double suggestedUnitPrice;

  private boolean reordered;

  private boolean replaced;

  private String supplierId;

  @JsonSerialize(using = IonLocalDateSerializer.class)
  @JsonDeserialize(using = IonLocalDateDeserializer.class)
  private LocalDate createdOn;
  private String createdBy;

  @JsonSerialize(using = IonLocalDateSerializer.class)
  @JsonDeserialize(using = IonLocalDateDeserializer.class)
  private LocalDate updatedOn;
  private String updatedBy;

  private ProductStatus productStatus;

  private String buyerName;

  private String buyerCellNumber;

  private double numInstallment;

  private double currentInstallment;

  private double recoveredAmount;

  private double remainingAmount;

  private double profit;

  private double adminComponentFromProfit;

  private double sellerComponentFromProfit;

  private double travelComponentFromProfit;

  private double ITComponentFromProfit;

  private double logisticComponentFromProfit;

  private double coreGroupMemberContributionComponentFromProfit;

  public Product(String id, int code, String type, String description, double buyUnitPrice, double suggestedUnitPrice) {
    super();
    this.id = id;
    this.code = code;
    this.type = type;
    this.description = description;
    this.buyUnitPrice = buyUnitPrice;
    this.suggestedUnitPrice = suggestedUnitPrice;
  }

}
