package com.lse.admin.model;

import java.time.LocalDate;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

public class Product {

  /**
   * internal id generated by the app
   */
  private final String id;

  /**
   * externally provided code; typically generated by the administration team
   */
  @JsonProperty("Generated-Id")
  private final String code;

  @JsonProperty("Type")
  private final String type;

  @JsonProperty("Description")
  private final String description;

  /**
   * price at which the product has been bought
   */
  @JsonProperty("Buy-Price")
  private double buyUnitPrice;

  /**
   * price at which the product has been planned to be sold
   */
  @JsonProperty("Sell-Price")
  private double suggestedUnitPrice;

  @JsonProperty("Is-Reordered")
  private boolean reordered;

  @JsonProperty("Is-Replaced")
  private boolean replaced;

  @JsonProperty("Supplier-Id")
  private String supplierId;

  @JsonSerialize(using = IonLocalDateSerializer.class)
  @JsonDeserialize(using = IonLocalDateDeserializer.class)
  private LocalDate createdOn;
  private String createdBy;

  @JsonSerialize(using = IonLocalDateSerializer.class)
  @JsonDeserialize(using = IonLocalDateDeserializer.class)
  private LocalDate updatedOn;
  private String updatedBy;

  private ProductStatus productStatus;

  public Product(String id, String code, String type, String description, double buyUnitPrice, double suggestedUnitPrice) {
    super();
    this.id = id;
    this.code = code;
    this.type = type;
    this.description = description;
    this.buyUnitPrice = buyUnitPrice;
    this.suggestedUnitPrice = suggestedUnitPrice;
  }

  public String getId() {
    return id;
  }

  public String getCode() {
    return code;
  }

  public String getType() {
    return type;
  }

  public String getDescription() {
    return description;
  }

  public double getBuyUnitPrice() {
    return buyUnitPrice;
  }

  public double getSuggestedUnitPrice() {
    return suggestedUnitPrice;
  }

  public boolean isReordered() {
    return reordered;
  }

  public boolean isReplaced() {
    return replaced;
  }

  public String getSupplierId() {
    return supplierId;
  }

  public LocalDate getCreatedOn() {
    return createdOn;
  }

  public String getCreatedBy() {
    return createdBy;
  }

  public LocalDate getUpdatedOn() {
    return updatedOn;
  }

  public String getUpdatedBy() {
    return updatedBy;
  }

  public ProductStatus getProductStatus() {
    return productStatus;
  }

}
